name: drupalonboarding
recipe: drupal10
config:
  webroot: docroot/web
services:
  appserver:
    type: php:8.3
  database:
    type: mariadb:10.6    
tooling:
  drush:
    service: appserver
    cmd: /app/docroot/vendor/bin/drush -r /app/docroot/web